version: "3.7"

services:
  database:
    image: postgres:12.4
    ports:
      - '5432:5432'
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: my-secure-passwd
      POSTGRES_USER: my-user
      POSTGRES_DB: gdatabase

  gservice:
    build: .
    restart: on-failure
    depends_on: 
      - database
    ports:
      - "3000:3000"
    environment: 
      POSTGRES_PASSWORD: my-secure-passwd
      POSTGRES_USER: my-user
      POSTGRES_DB: gdatabase
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: 3000

volumes:
  pg-data: {}